In [18]:
import pandas as pd 
import pymongo as pym

In [19]:
#Making Mongo DB connection
client = pym.MongoClient('mongodb://localhost:27017')

In [20]:
data_from_db =db.raw_tweets.find({},{'_id':0})

In [21]:
data_from_db

In [22]:
pd.DataFrame.from_dict(data_from_db)

,user_name,user_id,tweet_id,text,retweet_count,tweet_date
0,Elon Musk,44196397,1533992088206921728,@PPathole It will be our best product ever imo,1331,06/07/2022
1,Elon Musk,44196397,1533857698575310848,"What resolution is life in, 8k? â€“ SJM",5170,06/06/2022
2,Elon Musk,44196397,1533839270976204801,@realMeetKevin Correct,1583,06/06/2022
3,Elon Musk,44196397,1533834416656486401,@realchrisrufo @Liv_Boeree There are still som...,824,06/06/2022
4,Elon Musk,44196397,1533834190600347648,@corkyjames @realchrisrufo ðŸ¤£,111,06/06/2022
...,...,...,...,...,...,...
195,Elon Musk,44196397,1530380264966434823,https://t.co/USLO967YsJ,103376,05/28/2022
196,Elon Musk,44196397,1530379867111542784,@harsimranbansal @PPathole @LouDobbs Incentive...,182,05/28/2022
197,Elon Musk,44196397,1530379410645319680,@archillect Pretty sure I saw that at Burning Man,357,05/28/2022
198,Elon Musk,44196397,1530358187706179585,@BillyM2k Seems like they would be pretty vuln...,298,05/28/2022
199,Elon Musk,44196397,1530355592564551682,@lexfridman We are all individuals!\nhttps://t...,635,05/28/2022